### PR TITLE
fix: Header layout when paused

### LINKED ISSUE #202: [Bug] Header layout is not maintained when Recorder is Paused
### Bug summary

When the recorder is in pause mode, the header's layout ceases to fill the entire area.

### Recorder Version

alpha-3

### Steps to reproduce

1. Start recording
2. Pause
3. Observe the layout change

### Expected behavior

The recorder's header should use the same layout regardless of recording status.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by justinkambic**
## Summary

Resolves #202.

Fixes header layout when Paused.

## Implementation details

One-line change.

### Before

image

### After

image

### CODE REVIEW

File: src/components/Header/HeaderControls.tsx [hunk 1]
```diff
@@ -110,7 +110,12 @@ export function HeaderControls({ setIsCodeFlyoutVisible }: IHeaderControls) {
           </ControlButton>
         </EuiFlexItem>
       )}
-      <EuiFlexItem grow={recordingStatus === RecordingStatus.Recording}>
+      <EuiFlexItem
+        grow={
+          recordingStatus === RecordingStatus.Recording ||
+          recordingStatus === RecordingStatus.Paused
+        }
+      >
```
Comment (kyungeunni) [inline src/components/Header/HeaderControls.tsx:118]: Would this work? (I've tested locally but not sure if I missed some reasons behind it)
```suggestion
      <EuiFlexItem grow>
```

Comment (kyungeunni) [inline src/components/Header/HeaderControls.tsx:118]: Would this work? (I've tested locally but not sure if I missed some reasons behind it)
```suggestion
      <EuiFlexItem grow>
```

Comment (justinkambic) [reply src/components/Header/HeaderControls.tsx:118]: No this won't work because we want it to `grow` only when status is `Recording` or `Paused`. When we are `NotRecording`, we want the URL input to expand to fill the rest of the space in this row. If we `grow` always, the input will not be able to fill the entire space:

image

vs. if we use the code as written:

image

Comment (justinkambic) [reply src/components/Header/HeaderControls.tsx:118]: Sometimes they're a necessary evil 😆
